### ISSUE TITLE
Website isn't shwon anymore on testserver

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#32]
After deploying on Jenkins the Website isn't shown anymore. It seems like it is an issue with AngularJS rather with the server setup because you are able to see the frontend html source code.

**Comment by danielreischl** [comment]
It seems so the reason is Chart.js. If i try to open the js code on the testserver, I get a 404.

**Comment by TobiDo** [comment]
It was a typo: the file is indeed named Chart.js but was linked as chart.js. Furthemore the file circleCarrier.js does not exist. I commented out the linking in index.html. Please add the file and uncomment the link to it.
General remark: I think we had a similar issue before. Please watch for such typos. Even more important: if you change something: make sure that it works or at least that nothing is broken.

As such I would say the issue is resolved. Although the missing file might cause other/different issues.

**Comment by danielreischl** [comment]
ok, I close it for now :) 

You can also close it later the next time :)
