### ISSUE TITLE
License Header

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#33]
Hey guys,

one requirement for next week is to add a license header to each source code file. I'm not sure how this has to look in the end but I found these information:

http://www.gnu.org/licenses/gpl-howto.en.html

Anyone a clue how the header has to look in the end?

**Comment by TobiDo** [comment]
Since we're just before midterm-release, it might even be a good time to reconsider our initial license decision altogether. The decision was made very early and with little knowledge about our specific project and about ups and downs of different lincences.
This is probably not the right place to discuss it in detail, I just wanted to raise the issue here, to avoid that we add the headers before we agree that we want to stick to the license or change it.

**Comment by danielreischl** [comment]
After the discussion yesterday:

Are we keeping the license and can we start adding the headers to the file?

**Comment by danielreischl** [comment]
should be done :+1:
