### ISSUE TITLE
BUG: empty carrierCompareList causes error message on both circle pages even though carriers are selected.

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#45]
if the array of selected carriers (carrierCompareList) is empty when coming from the circle page, the alert alert("You did not chose any Carriers to compare") is given, when refreshing the graph plot, even though some carriers have been selected from the checkboxes. This happens on both graph pages.

**Comment by deadlmaster** [comment]
> if the array of selected carriers (carrierCompareList) is empty when coming from the circle page, the alert alert("You did not chose any Carriers to compare") is given

okay so far so good. That is what the message should do since you did not select a carrier.

> when refreshing the graph plot, even though some carriers have been selected from the checkboxes

I do not understand what you did. Did I understand correctly, that you selected some checkboxes, hit the button refresh, and an alert message popped up? I just tested it and it worked for me in the average consumption view

**Comment by ghost** [comment]
Tested it again, it works. Either something changed or i was wrong ;)

**Comment by deadlmaster** [comment]
Did not change anything, but as long as it works thats fine :smile:
