### ISSUE TITLE
Carrier colors only appear after clicking a carrier on the page

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#55]
Normally the carriers should be colored right when the page is loaded. However, there is no color when you enter the page. After clicking one carrier, the color appears for all of them.

Ideally, the carriers should be colored right from the beginning. Maybe after loading all of the carriers with their color in the HTML document we can refresh them somehow?

**Comment by abhinavpuri** [comment]
When I am opening the site now, this issue seems to have been fixed. If someone worked on it, then shall we close this issue?

**Comment by danielreischl** [comment]
It can't be fixed right now because there was no commit since then :'D

**Comment by TobiDo** [comment]
Bad news first: I am about to extend this bug to the circle page. That is the circles will only show up after an additional reload.
Good news: I think I found the root of the bug. It seems as if Papa parse uses an asynchronous XMLHttpRequest to fetch the csv file. Then the painting of the carriers starts before the percentage data is actually written by papa parse. Unfortunately there does not seem to be an option to use synchronous requests in papa parse. If I am wrong please let me know. Otherwise I will implement an easy workaround by first getting the file synchronously and then feeding it into papa.

EDIT: However, I saw that the circles, of course, already use papa parse in the current version. So maybe I still don't know where it comes from.

**Comment by danielreischl** [comment]
We could also do a workaround and avoiding the csv file by just calling the percentage directly. we could easily add it to values.request.

**Comment by ghost** [comment]
this is fixed
