### ISSUE TITLE
Sessions selection

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#59]
Right now all four CSV files from the industry partner get processed and saved as different sessions. So we can include the session selection too to the graph pages.

1: We need a query from the database that lets us know how many sessions we have, right @AMOSus .

2: We need the possibilities to select buttons with the sessions.

3: We need queries that deliver us the data for the selected sessions, this is already working right @AMOSus ?

**Comment by danielreischl** [comment]
1. It's already since the last sprint implemented (Value current session):
   https://github.com/AMOSus/amos-ss16-proj6/wiki/Connection-of-AngularJS-(Frontend)-to-Django-(Middleware)#request-values 
2. That's true and is part of the current UserStory 86
3. Yes it is at least for the average graph:
   https://github.com/AMOSus/amos-ss16-proj6/wiki/Connection-of-AngularJS-(Frontend)-to-Django-(Middleware)#request-values 

The continouse graph isn't documented. Have to look up what @TobiDo did.

**Comment by danielreischl** [comment]
And this is not really an enhancement. It is just part of the UserStory for this week.

**Comment by danielreischl** [comment]
To 3. Just looked it up. Yes it's implemented.
