### ISSUE TITLE
Position is going down again/still

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#71]
Somthing is wrong with the dataProcessing-Scripts:

Energy is dropping to Zero and Position is going down. Both should be case, right?

![image](https://cloud.githubusercontent.com/assets/18442099/16272578/916d5394-389e-11e6-9b15-e72ae47e994d.png)

![image](https://cloud.githubusercontent.com/assets/18442099/16272593/9fd60980-389e-11e6-8e1c-c41587a498c2.png)

It's kinda at same timestamp

**Comment by ghost** [comment]
would be awesome if you could name the graph where this occurs

**Comment by ghost** [comment]
and maybe also which data file

**Comment by danielreischl** [comment]
trace DV

![image](https://cloud.githubusercontent.com/assets/18442099/16273936/cbef2894-38a3-11e6-894c-f5a6f3a7a576.png)

A couple of times. Just load it and select the last iterations for all carriers and you will see it.

**Comment by ghost** [comment]
weird that its ONLY happening on DV and on the other files not at all ...

**Comment by ghost** [comment]
What was DV again? Maybe it was the file where they interrupted manually and that messes with the algorithm? So when they stopped the carrier manually, the position was actually going backwards because they were shoving it back..

**Comment by danielreischl** [comment]
yeah that was also my idea in this moment but I thought DV is "Dauerhafte Verschmutzung".

**Comment by ghost** [comment]
Hmm then i need to have a closer look

**Comment by danielreischl** [comment]
It is also in PE.

**Comment by ghost** [comment]
Wow i finally found out that this bug happens due to corrupt data files that show just zeros for all the energy consumptions (Trace DV for example has all zeros from timestamp 108603 to 109154). Therefore we see all the energy consumption in this time go to zero (in this case in the middle of iteration 4).

<img width="1680" alt="bildschirmfoto 2016-06-25 um 18 37 48" src="https://cloud.githubusercontent.com/assets/18442111/16357899/fc11dc6c-3b03-11e6-9d39-a0579151fc96.png">
<img width="604" alt="bildschirmfoto 2016-06-25 um 18 37 56" src="https://cloud.githubusercontent.com/assets/18442111/16357900/fc13c7d4-3b03-11e6-98c5-2bf34f4f5139.png">

The algorithm works fine.

**Comment by ghost** [comment]
However I found another huge bug in the process. The energy consumption was actually not aggregated.. Now we should se a change in all the energy consumption measures. Sorry for that. This happened due to me fixing the "first" position bug last week.

**Comment by ghost** [comment]
Also there are sometimes slight rollbacks in the position. This is however normal for some carriers to go back a little bit. I tested it and it is not due to the compression of the data. This can also be seen in the original data files.
